apiVersion: mcp.v2dy.org/v1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: project
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-mcp-apikey-secrets-sample
spec:
  legacy: false
  url: "https://api.example.com/openapi.json"
  basePath: "/api/v1"
  replicas: 1
  auth:
    apiKey:
      location: "header"
      name: "X-API-Key"
      value:
        secretRef:
          name: "api-key-credentials"
          key: "api-key"
---
apiVersion: v1
kind: Secret
metadata:
  name: api-key-credentials
type: Opaque
data:
  api-key: bXktYXBpLWtleS12YWx1ZQ== # base64 encoded "my-api-key-value"
