apiVersion: mcp.v2dy.github.io/v1
kind: MCPServer
metadata:
  namespace: default
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample4
spec:
  replicas: 1
  url: "https://raw.githubusercontent.com/open-meteo/open-meteo/refs/heads/main/openapi.yml"
  basePath: "https://api.open-meteo.com"